eureka:
   client:
      register-with-url: true
      fetch-registry: true
      serive-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost

microservice:
   payment-service:
      endpoints:
         endpoint:
            uri: http://PAYMENT-SERVICE/payment/doPayment123
   order-service:
       endpoints:
          endpoint:
             uri: http://ORDER-SERVICE/order/bookOrder
